version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "1234:3000"
    depends_on:
      - mongo # This service depends on mongo. Start that first.
    links:
      - mongo
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend


  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend


networks:
  backend:

volumes:
  db-data:

